NAME = scavtrap

HEADERS = ClapTrap.hpp ScavTrap.hpp

SRCS = main.cpp ClapTrap.cpp ScavTrap.cpp

FLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++

.PHONY:		all

all: $(HEADERS)
	$(CC) $(FLAGS) $(SRCS) -o $(NAME)
